FC          = gfortran

FDEBUG      = -Wall -pedantic -fbackslash -ffixed-line-length-132 \
-fno-second-underscore -fbounds-check \
-ffpe-trap=invalid,zero,overflow,underflow -fdump-core -fbacktrace -ggdb3

FOPTIMIZED  = -Wall -fbackslash -ffixed-line-length-132 -fno-second-underscore \
-fbounds-check -fbounds-check \
-ffpe-trap=invalid,zero,overflow,underflow -fdump-core -fbacktrace -ggdb3 -O

#FFLAGS = $(FDEBUG)
FFLAGS = $(FOPTIMIZED)

TARGET = profiles_hdf5

OBJECTS = profiles_hdf5.o
MODULES = pro_modules.o

profiles_hdf5: $(OBJECTS) pro_subroutines.o $(MODULES) pro_modules.f
	$(FC) $(FFLAGS) $(INC) $(LIB) $(OBJECTS) pro_subroutines.o $(MODULES) -o $(TARGET)

profiles_hdf5.o:  profiles_hdf5.f pro_subroutines.o $(MODULES)
	$(FC) $(FFLAGS) $(INC) profiles_hdf5.f -c

pro_subroutines.o:  pro_subroutines.f $(MODULES)
	$(FC) $(FFLAGS) $(INC) pro_subroutines.f -c

pro_modules.o:  pro_modules.f
	$(FC) $(FFLAGS) $(INC) pro_modules.f -c

clean:
	rm pro_modules.o
	rm pro_subroutines.o
	rm profiles_hdf5.o
	rm profiles_hdf5
