#!/bin/bash
printf "USAGE: compile <filename>\n"
printf "Compiles a FORTRAN77 code. Filename WITHOUT .f!\n"
g77 -Wall -Wsurprising -W -ffast-math -funroll-all-loops -ffortran-bounds-check -pedantic -ffixed-line-length-none -finit-local-zero -o $1 $1'.f'
